;;; doom-omarchy-theme.el --- Omarchy-driven Doom theme -*- lexical-binding: t; no-byte-compile: t; -*-
;;
;; Generated by the omarchy-doom plugin from the active Omarchy theme
;; (colors.toml). Do not edit by hand: regenerate it by re-applying the
;; Omarchy theme or running `omarchy theme refresh'.
;;
;;; Commentary:
;; A Doom theme (doom-themes) port of the active Omarchy color scheme.
;; The hex values are baked in by the Omarchy template engine at theme-set
;; time: base0..base8 are a ramp between the theme's background and its
;; bright foreground, and derived hues (bg-alt, vertical-bar, dark-blue,
;; violet, cyan, dark-cyan, dark-green) are mixes of the base palette.
;;
;; Palette entries use the standard Doom triple form (gui, 256, 16) because
;; doom-themes-base resolves some of them with (car ...) directly; the
;; third column is a best-effort ANSI name for low-color terminals.
;;; Code:

(require 'doom-themes)

;;; Variables

(defgroup doom-omarchy-theme nil
  "Options for the Omarchy-driven Doom theme."
  :group 'doom-themes)

(defcustom doom-omarchy-brighter-modeline nil
  "If non-nil, more vivid colors will be used to style the mode-line."
  :group 'doom-omarchy-theme
  :type 'boolean)

(defcustom doom-omarchy-brighter-comments nil
  "If non-nil, comments will be highlighted in more vivid colors."
  :group 'doom-omarchy-theme
  :type 'boolean)

(defcustom doom-omarchy-comment-bg doom-omarchy-brighter-comments
  "If non-nil, comments will have a subtle, darker background."
  :group 'doom-omarchy-theme
  :type 'boolean)

(defcustom doom-omarchy-padded-modeline t
  "If non-nil, adds a 4px padding to the mode-line."
  :group 'doom-omarchy-theme
  :type '(or integer boolean))


;;; Theme definition

(def-doom-theme doom-omarchy
  "A Doom theme generated from the active Omarchy theme colors."

  ;; Color scheme (generated from colors.toml)
  ;; name          gui                       256                       16
  ((bg            '("#{{ background_strip }}"          "#{{ background_strip }}"          "black"))
   (bg-alt        '("#{{ darker_background_strip }}"   "#{{ darker_background_strip }}"   "brightblack"))
   (base0         '("#{{ mix_strip background bright_foreground 0.18 }}" "#{{ mix_strip background bright_foreground 0.18 }}" "black"))
   (base1         '("#{{ mix_strip background bright_foreground 0.27 }}" "#{{ mix_strip background bright_foreground 0.27 }}" "brightblack"))
   (base2         '("#{{ mix_strip background bright_foreground 0.36 }}" "#{{ mix_strip background bright_foreground 0.36 }}" "brightblack"))
   (base3         '("#{{ mix_strip background bright_foreground 0.45 }}" "#{{ mix_strip background bright_foreground 0.45 }}" "brightblack"))
   (base4         '("#{{ mix_strip background bright_foreground 0.54 }}" "#{{ mix_strip background bright_foreground 0.54 }}" "brightblack"))
   (base5         '("#{{ mix_strip background bright_foreground 0.63 }}" "#{{ mix_strip background bright_foreground 0.63 }}" "brightblack"))
   (base6         '("#{{ mix_strip background bright_foreground 0.72 }}" "#{{ mix_strip background bright_foreground 0.72 }}" "brightblack"))
   (base7         '("#{{ mix_strip background bright_foreground 0.81 }}" "#{{ mix_strip background bright_foreground 0.81 }}" "brightblack"))
   (base8         '("#{{ bright_foreground_strip }}"   "#{{ bright_foreground_strip }}"   "white"))
   (fg            '("#{{ foreground_strip }}"          "#{{ foreground_strip }}"          "white"))
   (fg-alt        '("#{{ light_foreground_strip }}"    "#{{ light_foreground_strip }}"    "brightwhite"))

   (accent        '("#{{ accent_strip }}"              "#{{ accent_strip }}"              "brightblue"))
   (grey          '("#{{ muted_strip }}"               "#{{ muted_strip }}"               "brightblack"))

   (red           '("#{{ red_strip }}"                 "#{{ red_strip }}"                 "red"))
   (orange        '("#{{ orange_strip }}"              "#{{ orange_strip }}"              "brightred"))
   (green         '("#{{ green_strip }}"               "#{{ green_strip }}"               "green"))
   (teal          '("#{{ cyan_strip }}"                "#{{ cyan_strip }}"                "brightgreen"))
   (yellow        '("#{{ yellow_strip }}"              "#{{ yellow_strip }}"              "yellow"))
   (blue          '("#{{ blue_strip }}"                "#{{ blue_strip }}"                "brightblue"))
   (dark-blue     '("#{{ mix_strip blue darker_background 0.55 }}" "#{{ mix_strip blue darker_background 0.55 }}" "blue"))
   (magenta       '("#{{ magenta_strip }}"             "#{{ magenta_strip }}"             "magenta"))
   (violet        '("#{{ mix_strip magenta bright_foreground 0.45 }}" "#{{ mix_strip magenta bright_foreground 0.45 }}" "brightmagenta"))
   (cyan          '("#{{ mix_strip cyan bright_foreground 0.35 }}" "#{{ mix_strip cyan bright_foreground 0.35 }}" "brightcyan"))
   (dark-cyan     '("#{{ mix_strip cyan darker_background 0.50 }}" "#{{ mix_strip cyan darker_background 0.50 }}" "cyan"))

   ;; Additional custom colors
   (dark-green    '("#{{ mix_strip green background 0.20 }}" "#{{ mix_strip green background 0.20 }}" "green"))
   (brown         '("#{{ brown_strip }}"                "#{{ brown_strip }}"                "yellow"))

   ;; Face categories -- required for all themes
   (highlight     accent)
   (vertical-bar  '("#{{ mix_strip background bright_foreground 0.12 }}" "#{{ mix_strip background bright_foreground 0.12 }}" "black"))
   (selection     base4)
   (builtin       red)
   (comments      (if doom-omarchy-brighter-comments base5 base1))
   (doc-comments  (doom-lighten comments 0.25))
   (constants     orange)
   (functions     blue)
   (keywords      magenta)
   (methods       blue)
   (operators     cyan)
   (type          base8)
   (strings       green)
   (variables     base8)
   (numbers       orange)
   (region        '("#{{ selection_background_strip }}" "#{{ selection_background_strip }}" "brightblack"))
   (error         red)
   (warning       yellow)
   (success       green)
   (vc-modified   orange)
   (vc-added      green)
   (vc-deleted    red)

   ;; Custom categories
   (hidden        bg)

   (-modeline-bright doom-omarchy-brighter-modeline)
   (-modeline-pad
    (when doom-omarchy-padded-modeline
      (if (integerp doom-omarchy-padded-modeline) doom-omarchy-padded-modeline 4)))

   (modeline-fg     'unspecified)
   (modeline-fg-alt base5)
   (modeline-bg
    (if -modeline-bright
        base3
      (doom-darken bg 0.15)))
   (modeline-bg-l
    (if -modeline-bright
        base3
      (doom-darken bg 0.10)))
   (modeline-bg-inactive   (doom-darken bg 0.10))
   (modeline-bg-inactive-l bg))


  ;; --- Extra faces ------------------------------
  (
   ;; Core
   (cursor :background "#{{ cursor_strip }}")
   ((region &override) :background region :distant-foreground (doom-darken fg 0.2) :extend t)
   (isearch :background yellow :foreground bg :distant-foreground bg)
   (lazy-highlight :background yellow :foreground bg :distant-foreground bg :weight 'bold)
   ((show-paren-match &override) :background highlight :foreground bg :distant-foreground base8 :weight 'bold)
   ((show-paren-mismatch &override) :background red :foreground bg :distant-foreground bg :weight 'bold)

   ;; Line numbers
   ((line-number &override) :foreground base4 :background (doom-darken bg 0.02))
   ((line-number-current-line &override) :foreground accent :background (doom-darken bg 0.04) :weight 'bold)

   ;; Comments
   (font-lock-comment-face
    :foreground comments
    :background (if doom-omarchy-comment-bg (doom-lighten bg 0.05) 'unspecified))
   (font-lock-doc-face
    :inherit 'font-lock-comment-face
    :foreground doc-comments)

   ;; ;;; Doom Modeline
   (doom-modeline-bar :background (if -modeline-bright modeline-bg highlight))
   (doom-modeline-buffer-path :foreground base8 :weight 'normal)
   (doom-modeline-buffer-file :foreground brown :weight 'normal)
   ((doom-modeline-persp-name &override) :foreground violet)
   ((doom-modeline-buffer-major-mode &override) :foreground violet)
   (mode-line
    :background modeline-bg :foreground modeline-fg
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg)))
   (mode-line-inactive
    :background modeline-bg-inactive :foreground modeline-fg-alt
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-inactive)))
   (mode-line-emphasis :foreground (if -modeline-bright base8 highlight))
   (mode-line-buffer-id :foreground highlight)

   ;; Solaire
   (solaire-mode-line-face
    :inherit 'mode-line
    :background modeline-bg-l
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-l)))
   (solaire-mode-line-inactive-face
    :inherit 'mode-line-inactive
    :background modeline-bg-inactive-l
    :box (if -modeline-pad `(:line-width ,-modeline-pad :color ,modeline-bg-inactive-l)))

   ;; Indentation
   (whitespace-indentation :background bg)
   (whitespace-tab :background bg)

   ;; Minibuffer / completions
   (minibuffer-prompt :foreground highlight :weight 'bold)
   ((completions-common-part &override) :foreground accent)
   ((completions-first-difference &override) :foreground fg-alt :weight 'bold)

   ;; Ivy / Vertico / Corfu
   (ivy-subdir :foreground blue)
   (ivy-minibuffer-match-face-1 :foreground green :background bg-alt)
   (ivy-minibuffer-match-face-2 :foreground orange :background bg-alt)
   (ivy-minibuffer-match-face-3 :foreground red :background bg-alt)
   (ivy-minibuffer-match-face-4 :foreground yellow :background bg-alt)
   (vertico-multiline :foreground comments)
   (vertico-candidate :foreground fg)
   (vertico-selected :background bg-alt :foreground fg :weight 'bold)
   (corfu-default :background bg-alt :foreground fg)

   ;; Rainbow delimiters
   (rainbow-delimiters-depth-1-face :foreground fg)
   (rainbow-delimiters-depth-2-face :foreground blue)
   (rainbow-delimiters-depth-3-face :foreground orange)
   (rainbow-delimiters-depth-4-face :foreground green)
   (rainbow-delimiters-depth-5-face :foreground cyan)
   (rainbow-delimiters-depth-6-face :foreground yellow)
   (rainbow-delimiters-depth-7-face :foreground teal)
   (rainbow-delimiters-unmatched-face :foreground red)

   ;; Treemacs
   (treemacs-root-face :foreground magenta :weight 'bold :height 1.2)
   (doom-themes-treemacs-root-face :foreground magenta :weight 'ultra-bold :height 1.2)
   (doom-themes-treemacs-file-face :foreground fg-alt)
   (treemacs-directory-face :foreground base8)
   (treemacs-file-face :foreground fg)
   (treemacs-git-modified-face :foreground green)
   (treemacs-git-renamed-face :foreground yellow)
   (treemacs-git-added-face :foreground green)
   (treemacs-git-deleted-face :foreground red)

   ;; Magit
   (magit-section-heading :foreground blue :weight 'bold)
   (magit-branch-remote :foreground orange)
   (magit-branch-local :foreground blue)
   ((magit-diff-added &override) :foreground green :background (doom-darken green 0.7))
   ((magit-diff-removed &override) :foreground red :background (doom-darken red 0.7))
   (git-commit-summary-face :foreground green)

   ;; Org
   (org-level-1 :foreground blue :weight 'bold :height 1.1)
   (org-level-2 :foreground magenta :weight 'bold)
   (org-level-3 :foreground cyan :weight 'bold)
   (org-level-4 :foreground yellow)
   (org-hide :foreground hidden)
   (org-code :foreground green)
   (org-verbatim :foreground yellow)
   (org-link :foreground cyan :underline t)
   ((org-done &override) :foreground green :weight 'bold)
   ((org-todo &override) :foreground red :weight 'bold)
   ((org-block &override) :background (doom-darken base2 0.65))
   ((org-block-begin-line &override) :background (doom-darken base2 0.65) :foreground comments :extend t)
   (org-quote :background (doom-darken bg 0.04) :foreground violet)
   (solaire-org-hide-face :foreground hidden)

   ;; Markdown
   (markdown-markup-face :foreground violet)
   (markdown-header-face :inherit 'bold :foreground dark-cyan)
   (markdown-blockquote-face :foreground violet :background (doom-lighten bg 0.04))
   (markdown-table-face :foreground violet :background (doom-lighten bg 0.04))
   ((markdown-code-face &override) :foreground dark-cyan :background (doom-lighten bg 0.04))

   ;; Eshell / shells
   ((eshell-prompt-face &override) :foreground accent :weight 'bold)
   ((shell-ellipsis-face &override) :foreground accent)))

(provide-theme 'doom-omarchy)
;;; doom-omarchy-theme.el ends here